//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiThu.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebMVCDbContext : DbContext
    {
        public WebMVCDbContext()
            : base("name=WebMVCDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_khoa> dbo_khoa { get; set; }
        public virtual DbSet<dbo_monhoc> dbo_monhoc { get; set; }
        public virtual DbSet<dbo_nganh> dbo_nganh { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
